# Generated by Django 3.0.6 on 2020-05-18 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Twitter', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='tweet',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
    ]
