# Generated by Django 3.0.6 on 2020-05-20 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Twitter', '0004_tweet_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='content',
            field=models.TextField(max_length=235),
        ),
        migrations.AlterField(
            model_name='tweet',
            name='content',
            field=models.TextField(max_length=235),
        ),
    ]
