# Generated by Django 3.0.6 on 2020-05-20 16:40

import Twitter.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Twitter', '0005_auto_20200520_1922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='image',
            field=models.ImageField(blank=True, upload_to='tweet_images/', validators=[Twitter.validators.validate_image_file]),
        ),
    ]
