# Generated by Django 3.0.6 on 2020-05-20 16:40

import Twitter.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='header_image',
            field=models.ImageField(blank=True, upload_to='profile_headers/', validators=[Twitter.validators.validate_image_file]),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(blank=True, default='userpick.webp', upload_to='user_icons/', validators=[Twitter.validators.validate_image_file]),
        ),
    ]
